### ISSUE TITLE
configureVPN.sh - VPN password Illegal opperator

### ISSUE THREAD

**Issue by Ethanol6** [kaydenvanrijn/CITSANDBOX-VPN-SETUP-LINUX#1]
When configureVPN.sh asks for the VPN password it skips this step due to an illegal operator `-s`. 

`read -rs`
or 
`read -r -s`
work fine in a terminal on their own but in the script 
`read -r -s`
does not work.

**Comment by kaydenvanrijn** [comment]
Please make a pull request with your fix for this
